FROM node:18-alpine AS build

WORKDIR /app

ENV VITE_API_URL=http://localhost:5180/api
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]